# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fishnet.ui'
#
# Created: Wed Oct 29 23:56:18 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_FishnetMainWindow(object):
    def setupUi(self, FishnetMainWindow):
        FishnetMainWindow.setObjectName("FishnetMainWindow")
        FishnetMainWindow.resize(1025, 743)
        self.centralwidget = QtWidgets.QWidget(FishnetMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.providerBox = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.providerBox.sizePolicy().hasHeightForWidth())
        self.providerBox.setSizePolicy(sizePolicy)
        self.providerBox.setMinimumSize(QtCore.QSize(100, 0))
        self.providerBox.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.providerBox.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.providerBox.setObjectName("providerBox")
        self.horizontalLayout_2.addWidget(self.providerBox)
        self.searchTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.searchTextBox.setObjectName("searchTextBox")
        self.horizontalLayout_2.addWidget(self.searchTextBox)
        self.searchButton = QtWidgets.QToolButton(self.centralwidget)
        self.searchButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(110, 0))
        self.searchButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.searchButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.searchAllButton = QtWidgets.QToolButton(self.centralwidget)
        self.searchAllButton.setEnabled(True)
        self.searchAllButton.setMinimumSize(QtCore.QSize(125, 0))
        self.searchAllButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.searchAllButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.searchAllButton.setObjectName("searchAllButton")
        self.horizontalLayout_2.addWidget(self.searchAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.clearAllButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearAllButton.sizePolicy().hasHeightForWidth())
        self.clearAllButton.setSizePolicy(sizePolicy)
        self.clearAllButton.setMinimumSize(QtCore.QSize(125, 0))
        self.clearAllButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.clearAllButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.clearAllButton.setObjectName("clearAllButton")
        self.horizontalLayout_3.addWidget(self.clearAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabsWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabsWidget.setObjectName("tabsWidget")
        self.horizontalLayout.addWidget(self.tabsWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        FishnetMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FishnetMainWindow)
        self.statusbar.setObjectName("statusbar")
        FishnetMainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(FishnetMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        FishnetMainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(FishnetMainWindow)
        self.toolBar.setObjectName("toolBar")
        FishnetMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDo_Something = QtWidgets.QAction(FishnetMainWindow)
        self.actionDo_Something.setObjectName("actionDo_Something")
        self.actionQuit = QtWidgets.QAction(FishnetMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(FishnetMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionManage_providers = QtWidgets.QAction(FishnetMainWindow)
        self.actionManage_providers.setObjectName("actionManage_providers")
        self.actionEdit_settings = QtWidgets.QAction(FishnetMainWindow)
        self.actionEdit_settings.setObjectName("actionEdit_settings")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionManage_providers)
        self.menuEdit.addAction(self.actionEdit_settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FishnetMainWindow)
        self.tabsWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(FishnetMainWindow)

    def retranslateUi(self, FishnetMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FishnetMainWindow.setWindowTitle(_translate("FishnetMainWindow", "F1s#n3t"))
        self.label.setText(_translate("FishnetMainWindow", "Search on"))
        self.providerBox.setText(_translate("FishnetMainWindow", "Select provider"))
        self.searchButton.setText(_translate("FishnetMainWindow", "Search"))
        self.searchAllButton.setText(_translate("FishnetMainWindow", "Search All"))
        self.clearAllButton.setText(_translate("FishnetMainWindow", "Clear"))
        self.menuFile.setTitle(_translate("FishnetMainWindow", "File"))
        self.menuHelp.setTitle(_translate("FishnetMainWindow", "Help"))
        self.menuEdit.setTitle(_translate("FishnetMainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("FishnetMainWindow", "toolBar"))
        self.actionDo_Something.setText(_translate("FishnetMainWindow", "Quit"))
        self.actionQuit.setText(_translate("FishnetMainWindow", "Quit"))
        self.actionAbout.setText(_translate("FishnetMainWindow", "About"))
        self.actionManage_providers.setText(_translate("FishnetMainWindow", "Manage providers"))
        self.actionEdit_settings.setText(_translate("FishnetMainWindow", "Edit settings"))

